---
title: "Practice Activity 9"
author: "Sara Goel"
format: html
editor: visual
---

```{r}
library(tidyverse)
```


```{r}
animals <- read_csv("mystery_animal.csv")
```

**Part 1**

```{r}
animal_lm <- animals |> 
  lm(weight_after ~ weight_before, data = _)
```

```{r}
animal_lm |> 
  broom::augment() |> 
  ggplot(mapping = aes(y = .resid, x = weight_before)) +
  geom_point()
```

**Part 2**

```{r}
qunif(p = 0.95, min = 1.5, max = 3.5, lower.tail = TRUE, log.p = FALSE)
```

```{r}
qnorm(0.10, mean  = 4.6, sd = 0.8)
```

```{r}
1 - pnorm(q = 5, mean = 4.6, sd = 0.8)
```

```{r}
1 - pchisq(q = 5, df = 4)
```

```{r}
troms <- rnorm(n = 100, mean = 4.6, sd = 0.8)
sum(troms < 4)
```

**Part 3**

```{r}
music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n = n_reed, df = 4)
  
  return(sum(trombones) + sum(cornets) + sum(reeds))
  
}

set.seed(1957)

my_weights <- rerun(.n = 1000, 
                    music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                    ) |> 
  flatten_dbl()
```

```{r}
sum(my_weights < 4532)
```

```{r}
sum(my_weights > 4532)
```

